### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Xhaf** [Katorone/AutoMelvorIdle#1]
While mining, this error occasionally gets thrown in the console:
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at sellItem (bank.js?270:357)
    at eval (userscript.html?id=556aad4d-62e2-4489-b2e4-3d565825f6bd:414)
```

line 414 in AutoMelvorIdle is:
`    sellItem(getBankId(sell[0]), sell[1]);`

which calls the following line (357) in bank.js and then throws the error above:
`    var itemName = items[bank[bankID].id].name;`

**Comment by Katorone** [comment]
Thanks for the report!  I'll investigate and see if I can reproduce this.
Are gems getting sold normally?

**Comment by Xhaf** [comment]
Yes, gems get sold. Let me know if you need more info :)

**Comment by Katorone** [comment]
Should be fixed in the current version of Melvor Idle.
